### ISSUE TITLE
模型参数缺失

### ISSUE THREAD

**Issue by ZJoYuan** [HaotianZhangAI4Science/SurfGen#1]
作者您好！在使用您提供的模型参数（https://drive.google.com/file/d/1tKIib7qRN5IdNXhVB_8v1EBYiWdU12v8/view?usp=share_link）运行gen.py时，出现下图报错
<img width="1257" alt="截屏2023-10-18 10 32 02" src="https://github.com/HaotianZhangAI4Science/SurfGen/assets/75797624/221cea4d-82f5-454b-8b72-b3c231542a9b">
请问您是否方便提供正确的.pt文件？

**Comment by HaotianZhangAI4Science** [comment]
Thanks for your reminder! I checked the file and found that I forgot to replace the new version of parameters. Now the link has been changed, hope you can benefit from it. I recognize that it may contain several bugs since the model has been updated, which is different from its original version (Jan-2022). So feel free to contact if you have any problems!
